services:
  database:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - travelplatform-network

volumes:
  mongo_data:

networks:
  travelplatform-network:
    external: true